#services:
#  database:
#    image: 'postgres:11.21-bullseye'
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_USER: 'dev'
#      POSTGRES_DB: 'eshop'
#      POSTGRES_PASSWORD: 'pass'

services:
  database:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'eshop'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'pass'
